
DROP TABLE IF EXISTS WeiZhang;
DROP TABLE IF EXISTS CheLiang;
DROP TABLE IF EXISTS LuDuiZhang;
DROP TABLE IF EXISTS SiJi;
DROP TABLE IF EXISTS XianLu;
DROP TABLE IF EXISTS CheDui;
DROP TABLE IF EXISTS DuiZhang;
DROP TABLE IF EXISTS RenYuan;

